name: Question
description: Ask a question about RushTI usage or configuration
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about RushTI? We're here to help!

  - type: textarea
    id: goal
    attributes:
      label: What are you trying to do?
      description: Describe what you're trying to accomplish with RushTI.
      placeholder: I want to...
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: Describe what you've already tried, including any task files or configurations.
      placeholder: I've tried...
    validations:
      required: false

  - type: input
    id: rushti-version
    attributes:
      label: RushTI Version
      description: Run `rushti --version` or check the version you downloaded
      placeholder: e.g., 1.5.0
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, error messages, or configuration details.
      placeholder: Any additional information...
    validations:
      required: false
